# Generated by Django 5.2.3 on 2025-06-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('PY', 'Python'), ('JV', 'Java'), ('JS', 'Javascript')], max_length=3)),
                ('code', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CA', 'Compilation Error'), ('SKP', 'Skipped'), ('PD', 'Pending')], default='PD', max_length=3)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
            ],
        ),
    ]
