# Generated by Django 5.2.3 on 2025-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_memory_submission_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='incorrect_testcase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
