# Generated by Django 5.2.4 on 2025-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_incorrect_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CA', 'Compilation Error'), ('RE', 'Runtime Error'), ('SKP', 'Skipped'), ('PD', 'Pending')], default='PD', max_length=3),
        ),
    ]
