# Generated by Django 5.2.4 on 2025-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
