# Generated by Django 5.2.3 on 2025-06-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('pid', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('statement', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('memory_limit', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('test_count', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='problems', to='app.category')),
            ],
        ),
    ]
