# Generated by Django 5.2.3 on 2025-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(default='1 \\le n \\le 10^6'),
            preserve_default=False,
        ),
    ]
