# Generated by Django 5.2.3 on 2025-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='Weird Algorithm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='pid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
