# Generated by Django 5.2.3 on 2025-06-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_name_alter_problem_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
