# Generated by Django 5.2.3 on 2025-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
