# Generated by Django 5.2.3 on 2025-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_note_problem_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, null=True),
        ),
    ]
