# Generated by Django 5.2.3 on 2025-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pid',
            field=models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
