# Generated by Django 5.2.3 on 2025-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints_tmp',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
