# Generated by Django 5.2.3 on 2025-07-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problem_constraints_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='constraints',
        ),
    ]
