# Generated by Django 5.2.3 on 2025-07-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_remove_problem_constraints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='constraints_tmp',
            new_name='constraints',
        ),
    ]
