# Generated by Django 5.2.3 on 2025-07-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_rename_constraints_tmp_problem_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='accepted_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
