# Generated by Django 5.2.4 on 2025-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_problem_accepted_submissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='acr_value',
            field=models.FloatField(default=0),
        ),
    ]
