# Generated by Django 5.2.4 on 2025-07-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_problem_acr_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='acr_value',
        ),
    ]
