# Generated by Django 5.2.4 on 2025-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_problem_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_io',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
