# Generated by Django 5.2.4 on 2025-07-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_problem_sample_io'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
    ]
